# Generated by Django 5.0 on 2024-01-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
