# Generated by Django 5.0 on 2024-01-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productsapp", "0003_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="img/None/no-img.jpg", upload_to="products/"
            ),
        ),
    ]
