# Generated by Django 5.0 on 2024-01-12 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cartapp", "0001_initial"),
        ("productsapp", "0004_alter_product_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="cartItem",
        ),
    ]
